@startuml AppMus
!pragma teoz true
skinparam Shadowing false
skinparam BoxPadding 60
skinparam responseMessageBelowArrow true
title inviter un utilisateur par email
autonumber 1 "<b>"
box
actor "utilisateur" as u
endbox
box
actor "Createur/Admin" as ca
endbox
box
participant Front as f
participant REST api as ra
database BD as bd 
endbox
box
participant "SMTP server" as ss
endbox
ca->f: envoyer un lien par email pour rejoindre un ensemble
activate f
alt#Gold #LightBlue tous les champs remplis, format de l'email verifié
f->b: POST
@enduml